/**
 * EOS Course Project API
 * Web API for EOS Course project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GetAllSensorDataResponse {
    temperature?: string;
    humidity?: string;
    lightIntensity?: string;
    pwmLightIntensity?: string;
    servoPositionFriendly?: GetAllSensorDataResponse.ServoPositionFriendlyEnum;
    servoPosition?: string;
    heaterStatus?: GetAllSensorDataResponse.HeaterStatusEnum;
}
// tslint:disable-next-line: no-namespace
export namespace GetAllSensorDataResponse {
    export type ServoPositionFriendlyEnum = 'Open' | 'Closed';
    export const ServoPositionFriendlyEnum = {
        Open: 'Open' as ServoPositionFriendlyEnum,
        Closed: 'Closed' as ServoPositionFriendlyEnum
    };
    export type HeaterStatusEnum = 'On' | 'Off';
    export const HeaterStatusEnum = {
        On: 'On' as HeaterStatusEnum,
        Off: 'Off' as HeaterStatusEnum
    };
}


