/**
 * EOS Course Project API
 * Web API for EOS Course project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SetHeaterStatusBody { 
    heaterStatus?: SetHeaterStatusBody.HeaterStatusEnum;
}
export namespace SetHeaterStatusBody {
    export type HeaterStatusEnum = 'On' | 'Off';
    export const HeaterStatusEnum = {
        On: 'On' as HeaterStatusEnum,
        Off: 'Off' as HeaterStatusEnum
    };
}


