/**
 * EOS Course Project API
 * Web API for EOS Course project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SetLightIntensityBody { 
    pwmLightIntensity?: number;
}

