/**
 * EOS Course Project API
 * Web API for EOS Course project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetAllSensorDataResponse {
    'temperature'?: string;
    'humidity'?: string;
    'lightIntensity'?: string;
    'servoPositionFriendly'?: GetAllSensorDataResponse.ServoPositionFriendlyEnum;
    'servoPosition'?: string;
    'heaterStatus'?: GetAllSensorDataResponse.HeaterStatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "string"
        },
        {
            "name": "humidity",
            "baseName": "humidity",
            "type": "string"
        },
        {
            "name": "lightIntensity",
            "baseName": "lightIntensity",
            "type": "string"
        },
        {
            "name": "servoPositionFriendly",
            "baseName": "servoPositionFriendly",
            "type": "GetAllSensorDataResponse.ServoPositionFriendlyEnum"
        },
        {
            "name": "servoPosition",
            "baseName": "servoPosition",
            "type": "string"
        },
        {
            "name": "heaterStatus",
            "baseName": "heaterStatus",
            "type": "GetAllSensorDataResponse.HeaterStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return GetAllSensorDataResponse.attributeTypeMap;
    }
}

export namespace GetAllSensorDataResponse {
    export enum ServoPositionFriendlyEnum {
        Open = <any> 'Open',
        Closed = <any> 'Closed'
    }
    export enum HeaterStatusEnum {
        On = <any> 'On',
        Off = <any> 'Off'
    }
}
